apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logopicker
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: logopicker
    spec:
      containers:
      - name: logopicker-app
        image: anthonydahanne/logopicker:latest
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod, k8s
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://logopicker-mysql:3306/logopicker
        - name: JAVA_OPTS
          value: " -Xmx256m -Xms256m"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - name: web
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /management/health
            port: web
        livenessProbe:
          httpGet:
            path: /management/health
            port: web
          initialDelaySeconds: 180

