apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logopicker-mysql
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: logopicker-mysql
    spec:
      containers:

      - name: mysql
        image: mysql:5.7.20
        env:
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MYSQL_DATABASE
          value: "logopicker"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: logopicker-mysql
  namespace: default
spec:
  selector:
    app: logopicker-mysql
  ports:
  - port: 3306
