apiVersion: v1
kind: Service
metadata:
  name: logopicker
  namespace: default
  labels:
    app: logopicker
spec:
  selector:
    app: logopicker
  type: LoadBalancer
  ports:
  - name: web
    port: 8080
